### PR TITLE
feat: add a spinner to the auto import alert

### LINKED ISSUE #345: Add animated spinner for repo auto import alert banner on `/repos` page
Just to make it clearer that something is happening in the background

### PR DESCRIPTION
**Pull request by patrickdevivo**
the message that's displayed when a repo auto import is running for the first time.

Closes #345 

image

### CODE REVIEW

**Comment by emilyvandewalle** [comment]
The spinner is quite subtle on the right, maybe we could add a `Loader` variant to the `Alert` component, like this?

image

**Comment by patrickdevivo** [comment]
@emilyvandewalle yep you're right - a `Loader` variant to the `Alert` component would be great here. In fact, I was thinking that the `Alert` component should let the icon be _any_ DOM element (or React component) vs relying the `variant` to drive that. So maybe the default is set according to the `variant`, but it can be overridden by an `icon` prop. What do you think @german-mergestat?

I will open a ticket in `block`

**Comment by patrickdevivo** [comment]
This PR: https://github.com/mergestat/blocks/pull/78 should enabled this

**Comment by patrickdevivo** [comment]
Latest commit refactors to look like this:

image

@emilyvandewalle @german-mergestat

**Pull request merged**
